function params = init_face_params()

global alpha
global kapa
global lambda
global alpha_2
global label_set
global bg_concept

params = struct('coordinate', 'faces', ...
                'alpha', alpha, ...
                'alpha_2',alpha_2, ...
                'label_set',label_set, ....
                'bg_concept', bg_concept, ...
                'kapa', kapa, ...
                'lambda', lambda, ...
                'neg_bag', false, ...
                'cut_crowds', true, ...         % (this may change)flag to decide whether or not to remove crowded scenes
                'cut_threshold', 30, ...        % max size of crowds in bags
                'opt_flag', 'MOSEK_NORM');      % kind of optimization performed

end
